### ISSUE TITLE
dts-bundle-generator automatically pulls in react-native type reference for web build

### ISSUE THREAD

**Issue by jamesreggio** [mayteio/use-pusher#16] opened 2020-07-29 00:11 UTC
We're using this package in a web product, and we're encountering issues during compilation because the type definitions reference the `react-native` types, which we haven't installed in our product.

Could you consider vendoring (copying in) the types you need from React Native so we're able to use this package from web products?

For reference, this is the error from the TypeScript compiler:

![Screen Shot 2020-07-28 at 17 11 29](https://user-images.githubusercontent.com/822205/88741791-6c413880-d0f5-11ea-8fe5-9f8dd80a0136.png)

**Comment by mayteio** [comment] 2020-07-29 00:16
Sure thing, apologies for that unexpected side effect. Are you able to find a work around for the bug in the meantime?

Would love to see how it's being used too!

**Comment by jamesreggio** [comment] 2020-07-29 00:30
Thanks for the quick response!

We have to vendor a copy of the library and remove the line — it's not pretty, but it works for now.

We're using it for an internal trailer management tool at [Convoy](convoy.com). Can't show you the tool, unfortnately.

**Comment by mayteio** [comment] 2020-08-18 22:31
Hey @jamesreggio I have moved that definition into `@harelpls/use-pusher/react-native/index.d.ts` with 6.0.3. Can you please check and let me know if that works for you?

**Comment by mayteio** [comment] 2020-08-19 00:41
Got to the bottom of this - dts-bundle-generator (which builds our .d.ts files) is pulling in react-native reference automatically. The bandaid solution is to just delete it before releasing to npm. Need to fix this automatically.

**Comment by mayteio** [comment] 2020-08-19 01:11
7.0.0* Did some major house work and upgraded deps (breaking). This package now uses `pusher-js@7.0.0`

**Comment by cowsrule** [comment] 2021-02-20 01:42
I can confirm this is solved. However there are straggling issues due to deps which are solved in https://github.com/mayteio/use-pusher/pull/46.

**Comment by mayteio** [comment] 2021-03-02 02:39
Nice! Fixed with `7.2.1`.

**Closed by mayteio** 2021-03-02 02:39 UTC
